name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the Terraform version

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} # Specify your AWS region

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.8'
    
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install boto3

      - name: Create lambda.zip
        run: |
         zip -j lambda.zip lambda_function.py

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
name: S3 File Transfer

jobs:
  upload-and-move-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload file to Source S3 Bucket
      run: |
        aws s3 cp path/to/your/file.txt s3://spdh-src-bucket245254/file.txt

    - name: Move file from Source to Destination S3 Bucket
      run: |
        aws s3 cp s3://spdh-src-bucket245254/file.txt s3://spdh-dest-bucket0178566/file.txt
        aws s3 rm s3://spdh-src-bucket245254/file.txt

